import { NFO_GENERATOR } from '../config';
import {
  getBackdropUrl,
  getPosterUrl,
  type TMDBMovieDetails,
  type TMDBSeasonDetails,
  type TMDBShowDetails,
} from '../tmdb';

function buildThumbTags(thumbs: Array<{ url: string | null; aspect: string }>): string {
  const tags = thumbs
    .filter((thumb): thumb is { url: string; aspect: string } => Boolean(thumb.url))
    .map(thumb => `  <thumb aspect="${thumb.aspect}">${escapeXml(thumb.url)}</thumb>`);

  if (tags.length === 0) return '';
  return `${tags.join('\n')}\n`;
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function generateTVShowNFO(show: TMDBShowDetails): string {
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');
  const posterUrl = getPosterUrl(show.poster_path, 'original');
  const backdropUrl = getBackdropUrl(show.backdrop_path, 'original');
  const thumbTags = buildThumbTags([
    { url: posterUrl, aspect: 'poster' },
    { url: backdropUrl, aspect: 'fanart' },
  ]);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by ${NFO_GENERATOR} at ${now} -->
<tvshow>
  <title>${escapeXml(show.name)}</title>
  <originaltitle>${escapeXml(show.original_name)}</originaltitle>
  <year>${show.first_air_date?.split('-')[0] || ''}</year>
  <premiered>${show.first_air_date || ''}</premiered>
  <status>${escapeXml(show.status || '')}</status>
  <plot>${escapeXml(show.overview)}</plot>
  <rating>${show.vote_average ?? ''}</rating>
  <tmdbid>${show.id}</tmdbid>
${thumbTags}  <generator>${NFO_GENERATOR}</generator>
</tvshow>
`;
}

export function generateSeasonNFO(showTitle: string, season: TMDBSeasonDetails): string {
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');
  const title = season.name || `Season ${season.season_number}`;
  const seasonPosterUrl = getPosterUrl(season.poster_path, 'original');
  const thumbTags = buildThumbTags([{ url: seasonPosterUrl, aspect: 'poster' }]);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by ${NFO_GENERATOR} at ${now} -->
<season>
  <title>${escapeXml(title)}</title>
  <seasonnumber>${season.season_number}</seasonnumber>
  <plot>${escapeXml(season.overview || '')}</plot>
  <premiered>${season.air_date || ''}</premiered>
  <tmdbid>${season.id}</tmdbid>
  <showtitle>${escapeXml(showTitle)}</showtitle>
${thumbTags}  <generator>${NFO_GENERATOR}</generator>
</season>
`;
}

export function generateEpisodeNFO(
  showTitle: string,
  tmdbId: number,
  season: number,
  episode: number,
  title: string,
  aired: string,
  plot: string,
  stillPath?: string,
): string {
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');
  const stillUrl = getBackdropUrl(stillPath, 'original');
  const thumbTags = buildThumbTags([{ url: stillUrl, aspect: 'thumb' }]);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by ${NFO_GENERATOR} at ${now} -->
<episodedetails>
  <title>${escapeXml(title)}</title>
  <season>${season}</season>
  <episode>${episode}</episode>
  <aired>${aired}</aired>
  <plot>${escapeXml(plot)}</plot>
  <showtitle>${escapeXml(showTitle)}</showtitle>
  <tmdbid>${tmdbId}</tmdbid>
${thumbTags}  <generator>${NFO_GENERATOR}</generator>
</episodedetails>
`;
}

export function generateMovieNFO(movie: TMDBMovieDetails): string {
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');
  const posterUrl = getPosterUrl(movie.poster_path, 'original');
  const backdropUrl = getBackdropUrl(movie.backdrop_path, 'original');
  const thumbTags = buildThumbTags([
    { url: posterUrl, aspect: 'poster' },
    { url: backdropUrl, aspect: 'fanart' },
  ]);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by ${NFO_GENERATOR} at ${now} -->
<movie>
  <title>${escapeXml(movie.title)}</title>
  <originaltitle>${escapeXml(movie.original_title)}</originaltitle>
  <year>${movie.release_date?.split('-')[0] || ''}</year>
  <premiered>${movie.release_date || ''}</premiered>
  <plot>${escapeXml(movie.overview)}</plot>
  <tagline>${escapeXml(movie.tagline || '')}</tagline>
  <runtime>${movie.runtime || ''}</runtime>
  <rating>${movie.vote_average ?? ''}</rating>
  <tmdbid>${movie.id}</tmdbid>
${thumbTags}  <generator>${NFO_GENERATOR}</generator>
</movie>
`;
}
